CREATE TABLE IF NOT EXISTS authors(
	id serial,
	name VARCHAR(255) NOT NULL,
	email VARCHAR(100) NOT NULL UNIQUE,
	description VARCHAR(400) NOT NULL,
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT TIMESTAMP
);